Repository AntonVanAssche/md-headers.nvim, pull requests merged in 2023-10, with the labels that each got.

#3 Enhancement: Configurable Title Color for Markdown Popup Windows
  README.md
  lua/md-headers/init.lua
Labels: enhancement

#6 Enhancement: Simplify README with Dedicated WIKI Pages and Automated Deployment
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/WIKI/Configuration.md
  .github/WIKI/Home.md
  .github/WIKI/Installation.md
  .github/WIKI/Limitations.md
  .github/WIKI/Usage.md
  .github/WIKI/_Footer.md
  .github/workflows/wiki.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#8 Enhancement: Add RMarkdown support
  plugin/md-headers.lua
Labels: enhancement

#11 Enhancement: Add Quarto support
  plugin/md-headers.lua
Labels: enhancement

#10 Html headers correctly parsed
  lua/md-headers/init.lua
Labels: enhancement

#4 Enhancement: Implement TreeSitter to Parse and Retrieve headings
  .gitignore
  lua/md-headers/init.lua
Labels: bug, enhancement, help wanted

#12 Documentation: Remove limitations Wiki Page
  .github/WIKI/Limitations.md
Labels: documentation

#14 Enhancement: Introduce Customizable Auto-Close Behavior for Popup Window Selections
  .github/WIKI/Configuration.md
  .github/WIKI/Installation.md
  .github/WIKI/Usage.md
  README.md
  lua/md-headers/init.lua
Labels: enhancement
